src/Labs/BackBundle/Entity/Post.php
<?php

namespace Labs\BackBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Post
 *
 * @ORM\Table(name="post")
 * @ORM\Entity(repositoryClass="Labs\BackBundle\Repository\PostRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class Post
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     *
     * @Vich\UploadableField(mapping="blog_image", fileNameProperty="imageName")
     *
     * @var File $imageFile
     */
    protected $imageFile;

    /**
     * @var string $imageName
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $imageName;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    protected $title;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    protected $content;


    /**
     * @var dateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    protected $created;


    /**
     * @Gedmo\Slug(fields={"title", "id"}, updatable=true, separator="_")
     * @ORM\Column(length=128, unique=true)
     */
    protected $slug;


    public function __construct()
    {
        $this->created = new \DateTime('now');
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param text $content
     *
     * @return Post
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return text
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return Post
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }


    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/posts';
    }


    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }


    /**
     * @return string
     */
    public function getAssertPath()
    {
        return $this->getUploadDir().'/'.$this->imageName;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Post
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->created = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return Post
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * Set slug
     *
     * @param string $slug
     *
     * @return Product
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

}

src/Labs/BackBundle/Entity/Project.php
<?php

namespace Labs\BackBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;



/**
 * Project
 *
 * @ORM\Table(name="project")
 * @ORM\Entity(repositoryClass="Labs\BackBundle\Repository\ProjectRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Project
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @Assert\NotNull(message="Entrez le nom du dossier")
     * @ORM\Column(name="name", type="string", length=255)
     */
    protected $name;

    /**
     * @var string
     * @Assert\NotNull(message="Entrez les caractérisques du project")
     * @ORM\Column(name="settings", type="text", length=255)
     */
    protected $settings;

    /**
     * @var string
     * @Assert\NotNull(message="Entrez la description de la rencontre")
     * @ORM\Column(name="content", type="text")
     */
    protected $content;

    /**
     * @var
     *
     * @ORM\Column(name="created", type="datetime")
     */
    protected $created;

    /**
     * @var
     * @ORM\OneToMany(targetEntity="Labs\BackBundle\Entity\Media", mappedBy="project", cascade={"remove"})
     */
    protected $medias;


    /**
     * @Gedmo\Slug(fields={"name", "id"})
     * @ORM\Column(length=128, unique=true)
     */
    protected $slug;


    public function __construct()
    {
        $this->created = new \DateTime('now');
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set content
     *
     * @param string $content
     *
     * @return Dossier
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }


    /**
     * Add media
     *
     * @param \Labs\BackBundle\Entity\Media $media
     *
     * @return Dossier
     */
    public function addMedia(\Labs\BackBundle\Entity\Media $media)
    {
        $this->medias[] = $media;

        return $this;
    }

    /**
     * Remove media
     *
     * @param \Labs\BackBundle\Entity\Media $media
     */
    public function removeMedia(\Labs\BackBundle\Entity\Media $media)
    {
        $this->medias->removeElement($media);
    }

    /**
     * Get medias
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMedias()
    {
        return $this->medias;
    }


    /**
     * @return mixed
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @param mixed $created
     */
    public function setCreated($created)
    {
        $this->created = $created;
    }

    /**
     * Set slug
     *
     * @param string $slug
     *
     * @return Product
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }


    /**
     * @return string
     */
    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/project';
    }

    /**
     * @return string
     */
    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    /**
     * @return string
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     * @param string $settings
     *
     * @return Project
     */
    public function setSettings($settings)
    {
        $this->settings = $settings;
        return $this;
    }

}

src/Labs/BackBundle/Form/ProjectType.php
<?php

namespace Labs\BackBundle\Form;

use Ivory\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array(
                'label' => false,
                'attr' => array('class' => 'form-control')
            ))
            ->add('settings', CKEditorType::class, array(
                'label' => false
            ))
            ->add('content', CKEditorType::class, array(
                'label' => false
            ))
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Labs\BackBundle\Entity\Project'
        ));
    }
}

src/Labs/BackBundle/Controller/ProjectController.php
<?php

namespace Labs\BackBundle\Controller;

use Labs\BackBundle\Entity\Dossier;
use Labs\BackBundle\Entity\Project;
use Labs\BackBundle\Form\DossierType;
use Labs\BackBundle\Form\DossierEditType;
use Labs\BackBundle\Form\ProjectEditType;
use Labs\BackBundle\Form\ProjectType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Class DossierController
 * @package Labs\BackBundle\Controller
 * @Route("/project")
 */
class ProjectController extends Controller
{
    /**
     * @Route("/", name="project_index")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $projects = $em->getRepository('LabsBackBundle:Project')->findAll();
        return $this->render('LabsBackBundle:Projects:index.html.twig', array(
            'projects' => $projects
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/create", name="project_create")
     */
    public function CreateAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if($form->isValid()){
            $em->persist($project);
            $em->flush();
            $this->addFlash('success', 'L\'enregistrement  a été fait avec succès');
            return $this->redirectToRoute('media_create',['project' => $project->getId()], 302);
        }
        return $this->render('LabsBackBundle:Projects:create.html.twig',array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Project $project
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/{id}/edit", name="project_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Project $project, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $projects = $em->getRepository('LabsBackBundle:Dossier')->find($project);
        if(null === $projects)
        {
            throw new NotFoundHttpException('Page Introuvable',null, 404);
        }
        $form = $this->createForm(ProjectEditType::class, $projects);
        $form->handleRequest($request);

        if($form->isValid()){
            $em->flush();
            $this->addFlash('success', 'La modification a été effectué');
            return $this->redirectToRoute('project_view', array('id' => $projects->getId()), 302);
        }
        return $this->render('LabsBackBundle:Projects:edit.html.twig',array(
            'form' => $form->createView(),
            'id'   => $projects->getId()
        ));
    }

    /**
     * @param Project $project
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/{id}/view", name="project_view")
     * @Method({"GET", "POST"})
     */
    public function ProjectViewAction( Project $project)
    {
        $em = $this->getDoctrine()->getManager();
        $projects = $em->getRepository('LabsBackBundle:Project')->getOneAndAssociation($project);
        if(null === $projects)
        {
            throw new NotFoundHttpException('Page Introuvable',null, 404);
        }
        return $this->render('LabsBackBundle:Projects:project_view.html.twig',array(
            'projects' => $projects
        ));
    }

    /**
     * @param Project $project
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/{id}/delete", name="project_delete")
     * @Method("GET")
     */
    public function deleteAction(Project $project)
    {
        $em = $this->getDoctrine()->getManager();
        $projects = $em->getRepository('LabsBackBundle:Project')->find($project);
        if(null === $projects)
            throw new NotFoundHttpException('Page Introuvable',null, 404);
        else
            $em->remove($projects);
        $em->flush();
        $this->addFlash('success', 'La suppression a été fait avec succès');
        return $this->redirectToRoute('project_index', array(), 302);
    }
    
    
}

src/Labs/BackBundle/Resources/views/Projects/create.html.twig
{% extends 'LabsUboldBundle::loyout_ubold.html.twig' %}
{% block title %}{{ 'About - Page | AGR' }}{% endblock %}
{% block body %}
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    {% if app.session.flashBag.has('success') %}
                        <div class="alert alert-success" role="alert">
                            {% for msg in app.session.flashBag.get('success') %}
                                <strong> Succès </strong>{{ msg }}.
                            {% endfor %}
                        </div>
                    {% endif %}

                    <h4 class="page-title">{{ 'Creation de la page About' }}</h4>
                    <ol class="breadcrumb">
                        <li>
                            <a href="{{ path('homepage') }}">{{ 'AGR' }}</a>
                        </li>
                        <li class="active">
                            {{ 'Page Project' }}
                        </li>
                    </ol>
                </div>
            </div>
            <!-- end Page Title -->

            <!-- page content -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box">
                        <h4 class="m-t-0 header-title"><b>{{ 'Formulaire de creation de la page project' }}</b></h4>
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_start(form, {'role': 'form', 'action': path('project_create'), 'attr': {'class': 'form-horizontal'}}) }}
                                <div class="form-group">
                                    <label class="col-md-2 control-label">{{ 'Titre du project' }}</label>
                                    <div class="col-md-10">
                                        {{ form_row(form.name) }}
                                        {{ form_errors(form.name) }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">{{ 'caractéristique du project' }}</label>
                                    <div class="col-md-10">
                                        {{ form_row(form.settings) }}
                                        {{ form_errors(form.settings) }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">{{ 'Contenu du project' }}</label>
                                    <div class="col-md-10">
                                        {{ form_row(form.content) }}
                                        {{ form_errors(form.content) }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-8 col-md-offset-2">
                                        <button type="submit" class="btn btn-primary">{{ 'Créer le project' }}</button>
                                    </div>
                                </div>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end page content -->
        </div>
    </div>
{% endblock %}

{% block javascripts %}{% endblock %}

src/Labs/BackBundle/Resources/views/Projects/edit.html.twig
{% extends 'LabsUboldBundle::loyout_ubold.html.twig' %}
{% block title %}{{ 'About - Page | AGR' }}{% endblock %}
{% block body %}
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    {% if app.session.flashBag.has('success') %}
                        <div class="alert alert-success" role="alert">
                            {% for msg in app.session.flashBag.get('success') %}
                                <strong> Succès </strong>{{ msg }}.
                            {% endfor %}
                        </div>
                    {% endif %}

                    <h4 class="page-title">{{ 'Creation de la page About' }}</h4>
                    <ol class="breadcrumb">
                        <li>
                            <a href="{{ path('homepage') }}">{{ 'AGR' }}</a>
                        </li>
                        <li class="active">
                            {{ 'Page Project' }}
                        </li>
                    </ol>
                </div>
            </div>
            <!-- end Page Title -->

            <!-- page content -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box">
                        <h4 class="m-t-0 header-title"><b>{{ 'Formulaire de modification de la page project' }}</b></h4>
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_start(form, {'role': 'form', 'action': path('project_edit', {'id' : id}), 'attr': {'class': 'form-horizontal'}}) }}
                                <div class="form-group">
                                    <label class="col-md-2 control-label">{{ 'Titre du project' }}</label>
                                    <div class="col-md-10">
                                        {{ form_row(form.name) }}
                                        {{ form_errors(form.name) }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">{{ 'caractéristique du project' }}</label>
                                    <div class="col-md-10">
                                        {{ form_row(form.settings) }}
                                        {{ form_errors(form.settings) }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">{{ 'Contenu du project' }}</label>
                                    <div class="col-md-10">
                                        {{ form_row(form.content) }}
                                        {{ form_errors(form.content) }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-8 col-md-offset-2">
                                        <button type="submit" class="btn btn-danger">{{ 'Modifier le project' }}</button>
                                    </div>
                                </div>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end page content -->
        </div>
    </div>
{% endblock %}

{% block javascripts %}{% endblock %}

src/Labs/BackBundle/Resources/views/Projects/index.html.twig
{% extends 'LabsUboldBundle::loyout_ubold.html.twig' %}
{% block title %}{{ 'Project - Page | AGR' }}{% endblock %}
{% block body %}
    <div class="content">
        <div class="container">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    {% if app.session.flashBag.has('success') %}
                        <div class="alert alert-success" role="alert">
                            {% for msg in app.session.flashBag.get('success') %}
                                <strong> Succès </strong>{{ msg }}.
                            {% endfor %}
                        </div>
                    {% endif %}

                    <h4 class="page-title">{{  'Page About' }}</h4>
                    <ol class="breadcrumb">
                        <li>
                            <a href="{{ path('homepage') }}">{{ 'AGR' }}</a>
                        </li>
                        <li class="active">
                            {{ 'Page About' }}
                        </li>
                    </ol>
                </div>
            </div>
            <!-- end Page Title -->
            <!-- page content -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box">
                        <h4 class="m-t-0 header-title"><b>{{ 'Page About' }}</b></h4>
                        <p class="text-muted font-13">
                            <span class="pull-left">Liste du contenu des project</span>
                            <span class="pull-right"> <a href="{{ path('project_create') }}" class="btn btn-primary btn-block">{{ 'Créer page project' }}</a> </span>
                        </p>
                        <div class="clearfix"></div>

                        <table data-toggle="table"
                               data-show-columns="false"
                               data-page-list="[5, 10, 20]"
                               data-page-size="5"
                               data-pagination="true" data-show-pagination-switch="true" class="table-bordered " class="padding-top-sm">
                            <thead>
                            <tr>
                                <th data-field="tite" data-switchable="false">{{ 'Titre' }}</th>
                                <th data-field="subtite" data-switchable="false">{{ 'Sous titre' }}</th>
                                <th data-field="name">{{ 'date' }}</th>
                                <th data-field="user-status" class="text-center">Edit</th>
                                <th data-field="user-del" class="text-center">Del</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for project in projects %}
                                <tr>
                                    <td><a href="{{ path('project_view', {'id' : project.id}) }}">{{ project.name }}</a></td>
                                    <td>{{ project.slug }}</td>
                                    <td>{{ project.created|date('Y-m-d') }}</td>
                                    <td><a class="btn btn-block btn-primary" href="{{ path('project_edit', {'id' : project.id }) }}">{{ "Modifier" }}</a></td>
                                    <td><a class="btn btn-block btn-danger" href="{{ path('project_delete', {'id' : project.id }) }}">{{ "Delete" }}</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- end page content -->
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/labsubold/assets/plugins/bootstrap-table/js/bootstrap-table.min.js') }}"></script>
    <script src="{{ asset('bundles/labsubold/assets/pages/jquery.bs-table.js') }}"></script>
{% endblock %}

src/Labs/BackBundle/Resources/views/Projects/project_view.html.twig
{% extends 'LabsUboldBundle::loyout_ubold.html.twig' %}
{% block title %}{{ 'Project - Page | AGR' }}{% endblock %}
{% block body %}
    <div class="content">
        <div class="container">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    {% if app.session.flashBag.has('success') %}
                        <div class="alert alert-success" role="alert">
                            {% for msg in app.session.flashBag.get('success') %}
                                <strong> Succès </strong>{{ msg }}.
                            {% endfor %}
                        </div>
                    {% endif %}

                    <h4 class="page-title">{{  'Page project view' }}</h4>
                    <ol class="breadcrumb">
                        <li>
                            <a href="{{ path('homepage') }}">{{ 'AGR' }}</a>
                        </li>
                        <li class="active">
                            {{ 'Page About' }}
                        </li>
                    </ol>
                </div>
            </div>
            <!-- end Page Title -->
            <!-- page content -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box">
                        <h4 class="m-t-0 header-title"><b>{{ 'Page view project' }}</b></h4>
                        <p class="text-muted font-13">
                            <span class="pull-left">view project</span>
                            <span class="pull-right"> <a href="{{ path('project_index') }}" class="btn btn-primary btn-block">{{ 'liste des projects' }}</a> </span>
                        </p>
                        <div class="clearfix"></div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box m-t-20">
                                    <h4 class="m-t-0"><b>{{ projects.name }}</b></h4>

                                    <hr/>
                                        {{ projects.content|raw }}
                                    <hr/>

                                    <h4> <i class="fa fa-paperclip m-r-10 m-b-10"></i> Attachments <span>({{ projects.medias|length }})</span> </h4>

                                    <div class="row">
                                        {% for media in projects.medias %}
                                            <div class="col-sm-2 col-xs-4">
                                                <a href="#"> <img src="{{ asset(media.assertPath) }}" alt="attachment" class="img-thumbnail img-responsive"> </a>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end page content -->
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/labsubold/assets/plugins/bootstrap-table/js/bootstrap-table.min.js') }}"></script>
    <script src="{{ asset('bundles/labsubold/assets/pages/jquery.bs-table.js') }}"></script>
{% endblock %}